window:
  decorations: transparent
  padding:
    x: 18
    y: 35
font:
  normal:
    family: 'Source Han Code JP'
    style: N
  size: 12.0
colors:
  primary:
    background: '#1d1f21'
    foreground: '#c5c8c6'
  cursor:
    text: CellBackground
    cursor: '#c5c8c6'
  selection:
    text: CellForeground
    # background: '#c5c8c6'
  normal:
    black:   '#282a2e'
    red:     '#a54242'
    green:   '#8c9440'
    yellow:  '#de935f'
    blue:    '#5f819d'
    magenta: '#85678f'
    cyan:    '#5e8d87'
    white:   '#707880'
  bright:
    black:   '#373b41'
    red:     '#cc6666'
    green:   '#b5bd67'
    yellow:  '#f0c674'
    blue:    '#81a2be'
    magenta: '#b294ba'
    cyan:    '#8abeb7'
    white:   '#c5c8c6'
