# format = """
# $directory\
# $git_status\
# $git_branch\
# $line_break\
# $character"""

format = """
$directory\
$line_break\
$character"""

[directory]
format = "$path"	
truncation_length = 1000
# truncate_to_repo = false

[git_status]
format = " $all_status"
conflicted = "[⚫︎](red)"
ahead = "[⚫︎](green)"
behind = "[⚫︎](green)"
diverged = "[⚫︎](red)"
untracked = "[⚫︎](green)"
stashed = ""
modified = "[⚫︎](red)"
staged = "[⚫︎](yellow)"
renamed = "[⚫︎](red)"
deleted = "[⚫︎](red)"

[git_branch]
format = " $branch"
