#!/bin/sh

# install vim plugins
if [ ! -e ~/.vim/bundle/neobundle.vim ]; then
    mkdir -p ~/.vim/bundle
    git clone https://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim
fi
vim $HOME/.vimrc +NeoBundleInstall +qall
