#!/usr/local/bin/zsh

# install vim plugins
if [ ! -e ~/.vim/autoload/plug.vim ]; then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
vim +PlugInstall +qall < /dev/tty

# compile lesskey
mkdir -p ~/.less
lesskey -o ~/.less/key ../less/key

for file in $(ls -1 $ZDOTDIR/zshrc*); do
  dotfile="$ZDOTDIR/.$(basename $file)"

  # create dot-prefixed symlink
  if [[ ! -e $dotfile ]]; then
    ln -s $file $dotfile
  fi

  # compile zsh script
  zcompile $dotfile
done
